language: node_js
node_js:
  - 14
before_install:
  # Repo for Yarn
  - echo 'Before Install:'
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qqqq yarn
  - npm ci -g codecov
cache:
  yarn: true
  directories:
    - node_modules
script:
  - yarn build
  - yarn ci:check && codecov
after_success:
  - echo 'After Success:'
  - bash <(curl -s https://codecov.io/bash)
